name: CI

on: [push, pull_request]

env:
  TEXLIVE_VERSION: 2022

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Setup
        run: |
          sudo apt-get install --yes poppler-utils
          source $CONDA/etc/profile.d/conda.sh
          conda env update -n base -f environment.yml
          conda activate
          python -m install_texlive -p $HOME/texlive -t $TEXLIVE_VERSION --collections='-a' --package-file tex-packages.txt --update

          # add to path for following steps
          echo "$HOME/texlive/$TEXLIVE_VERSION/bin/x86_64-linux" >> $GITHUB_PATH
          export PATH="$HOME/texlive/$TEXLIVE_VERSION/bin/x86_64-linux:$PATH"
          tlmgr install --with-doc tex-overview

          # generate the lualatex font cache, otherwise it is done in parallel when calling make
          luaotfload-tool --update --force

          # copy latexmkrc to make sure its used also for vXXX
          mkdir -p ~/.config/latexmk
          cp common/latexmkrc ~/.config/latexmk/

      - name: Build
        run: |
          source $CONDA/etc/profile.d/conda.sh
          conda activate
          make -j 2

      - name: check for errors
        if: always()
        run: "! grep -R --include='*.log' '^!' -A 5 -B 5"
